// flow-typed signature: c4619222f58478e0548e9023dcbd7602
// flow-typed version: <<STUB>>/ajv_v^8.6.3/flow_v0.167.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ajv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ajv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ajv/dist/2019' {
  declare module.exports: any;
}

declare module 'ajv/dist/2020' {
  declare module.exports: any;
}

declare module 'ajv/dist/ajv' {
  declare module.exports: any;
}

declare module 'ajv/dist/compile/codegen/code' {
  declare module.exports: any;
}

declare module 'ajv/dist/compile/codegen' {
  declare module.exports: any;
}

declare module 'ajv/dist/compile/codegen/scope' {
  declare module.exports: any;
}

declare module 'ajv/dist/compile/errors' {
  declare module.exports: any;
}

declare module 'ajv/dist/compile' {
  declare module.exports: any;
}

declare module 'ajv/dist/compile/jtd/parse' {
  declare module.exports: any;
}

declare module 'ajv/dist/compile/jtd/serialize' {
  declare module.exports: any;
}

declare module 'ajv/dist/compile/jtd/types' {
  declare module.exports: any;
}

declare module 'ajv/dist/compile/names' {
  declare module.exports: any;
}

declare module 'ajv/dist/compile/ref_error' {
  declare module.exports: any;
}

declare module 'ajv/dist/compile/resolve' {
  declare module.exports: any;
}

declare module 'ajv/dist/compile/rules' {
  declare module.exports: any;
}

declare module 'ajv/dist/compile/util' {
  declare module.exports: any;
}

declare module 'ajv/dist/compile/validate/applicability' {
  declare module.exports: any;
}

declare module 'ajv/dist/compile/validate/boolSchema' {
  declare module.exports: any;
}

declare module 'ajv/dist/compile/validate/dataType' {
  declare module.exports: any;
}

declare module 'ajv/dist/compile/validate/defaults' {
  declare module.exports: any;
}

declare module 'ajv/dist/compile/validate' {
  declare module.exports: any;
}

declare module 'ajv/dist/compile/validate/keyword' {
  declare module.exports: any;
}

declare module 'ajv/dist/compile/validate/subschema' {
  declare module.exports: any;
}

declare module 'ajv/dist/core' {
  declare module.exports: any;
}

declare module 'ajv/dist/jtd' {
  declare module.exports: any;
}

declare module 'ajv/dist/refs/json-schema-2019-09' {
  declare module.exports: any;
}

declare module 'ajv/dist/refs/json-schema-2020-12' {
  declare module.exports: any;
}

declare module 'ajv/dist/refs/jtd-schema' {
  declare module.exports: any;
}

declare module 'ajv/dist/runtime/equal' {
  declare module.exports: any;
}

declare module 'ajv/dist/runtime/parseJson' {
  declare module.exports: any;
}

declare module 'ajv/dist/runtime/quote' {
  declare module.exports: any;
}

declare module 'ajv/dist/runtime/re2' {
  declare module.exports: any;
}

declare module 'ajv/dist/runtime/timestamp' {
  declare module.exports: any;
}

declare module 'ajv/dist/runtime/ucs2length' {
  declare module.exports: any;
}

declare module 'ajv/dist/runtime/validation_error' {
  declare module.exports: any;
}

declare module 'ajv/dist/standalone' {
  declare module.exports: any;
}

declare module 'ajv/dist/standalone/instance' {
  declare module.exports: any;
}

declare module 'ajv/dist/types' {
  declare module.exports: any;
}

declare module 'ajv/dist/types/json-schema' {
  declare module.exports: any;
}

declare module 'ajv/dist/types/jtd-schema' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/applicator/additionalItems' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/applicator/additionalProperties' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/applicator/allOf' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/applicator/anyOf' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/applicator/contains' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/applicator/dependencies' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/applicator/dependentSchemas' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/applicator/if' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/applicator' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/applicator/items' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/applicator/items2020' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/applicator/not' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/applicator/oneOf' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/applicator/patternProperties' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/applicator/prefixItems' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/applicator/properties' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/applicator/propertyNames' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/applicator/thenElse' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/code' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/core/id' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/core' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/core/ref' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/discriminator' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/discriminator/types' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/draft2020' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/draft7' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/dynamic/dynamicAnchor' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/dynamic/dynamicRef' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/dynamic' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/dynamic/recursiveAnchor' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/dynamic/recursiveRef' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/errors' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/format/format' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/format' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/jtd/discriminator' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/jtd/elements' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/jtd/enum' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/jtd/error' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/jtd' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/jtd/metadata' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/jtd/nullable' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/jtd/optionalProperties' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/jtd/properties' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/jtd/ref' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/jtd/type' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/jtd/union' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/jtd/values' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/metadata' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/next' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/unevaluated' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/unevaluated/unevaluatedItems' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/unevaluated/unevaluatedProperties' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/validation/const' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/validation/dependentRequired' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/validation/enum' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/validation' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/validation/limitContains' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/validation/limitItems' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/validation/limitLength' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/validation/limitNumber' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/validation/limitProperties' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/validation/multipleOf' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/validation/pattern' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/validation/required' {
  declare module.exports: any;
}

declare module 'ajv/dist/vocabularies/validation/uniqueItems' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ajv/dist/2019.js' {
  declare module.exports: $Exports<'ajv/dist/2019'>;
}
declare module 'ajv/dist/2020.js' {
  declare module.exports: $Exports<'ajv/dist/2020'>;
}
declare module 'ajv/dist/ajv.js' {
  declare module.exports: $Exports<'ajv/dist/ajv'>;
}
declare module 'ajv/dist/compile/codegen/code.js' {
  declare module.exports: $Exports<'ajv/dist/compile/codegen/code'>;
}
declare module 'ajv/dist/compile/codegen/index' {
  declare module.exports: $Exports<'ajv/dist/compile/codegen'>;
}
declare module 'ajv/dist/compile/codegen/index.js' {
  declare module.exports: $Exports<'ajv/dist/compile/codegen'>;
}
declare module 'ajv/dist/compile/codegen/scope.js' {
  declare module.exports: $Exports<'ajv/dist/compile/codegen/scope'>;
}
declare module 'ajv/dist/compile/errors.js' {
  declare module.exports: $Exports<'ajv/dist/compile/errors'>;
}
declare module 'ajv/dist/compile/index' {
  declare module.exports: $Exports<'ajv/dist/compile'>;
}
declare module 'ajv/dist/compile/index.js' {
  declare module.exports: $Exports<'ajv/dist/compile'>;
}
declare module 'ajv/dist/compile/jtd/parse.js' {
  declare module.exports: $Exports<'ajv/dist/compile/jtd/parse'>;
}
declare module 'ajv/dist/compile/jtd/serialize.js' {
  declare module.exports: $Exports<'ajv/dist/compile/jtd/serialize'>;
}
declare module 'ajv/dist/compile/jtd/types.js' {
  declare module.exports: $Exports<'ajv/dist/compile/jtd/types'>;
}
declare module 'ajv/dist/compile/names.js' {
  declare module.exports: $Exports<'ajv/dist/compile/names'>;
}
declare module 'ajv/dist/compile/ref_error.js' {
  declare module.exports: $Exports<'ajv/dist/compile/ref_error'>;
}
declare module 'ajv/dist/compile/resolve.js' {
  declare module.exports: $Exports<'ajv/dist/compile/resolve'>;
}
declare module 'ajv/dist/compile/rules.js' {
  declare module.exports: $Exports<'ajv/dist/compile/rules'>;
}
declare module 'ajv/dist/compile/util.js' {
  declare module.exports: $Exports<'ajv/dist/compile/util'>;
}
declare module 'ajv/dist/compile/validate/applicability.js' {
  declare module.exports: $Exports<'ajv/dist/compile/validate/applicability'>;
}
declare module 'ajv/dist/compile/validate/boolSchema.js' {
  declare module.exports: $Exports<'ajv/dist/compile/validate/boolSchema'>;
}
declare module 'ajv/dist/compile/validate/dataType.js' {
  declare module.exports: $Exports<'ajv/dist/compile/validate/dataType'>;
}
declare module 'ajv/dist/compile/validate/defaults.js' {
  declare module.exports: $Exports<'ajv/dist/compile/validate/defaults'>;
}
declare module 'ajv/dist/compile/validate/index' {
  declare module.exports: $Exports<'ajv/dist/compile/validate'>;
}
declare module 'ajv/dist/compile/validate/index.js' {
  declare module.exports: $Exports<'ajv/dist/compile/validate'>;
}
declare module 'ajv/dist/compile/validate/keyword.js' {
  declare module.exports: $Exports<'ajv/dist/compile/validate/keyword'>;
}
declare module 'ajv/dist/compile/validate/subschema.js' {
  declare module.exports: $Exports<'ajv/dist/compile/validate/subschema'>;
}
declare module 'ajv/dist/core.js' {
  declare module.exports: $Exports<'ajv/dist/core'>;
}
declare module 'ajv/dist/jtd.js' {
  declare module.exports: $Exports<'ajv/dist/jtd'>;
}
declare module 'ajv/dist/refs/json-schema-2019-09/index' {
  declare module.exports: $Exports<'ajv/dist/refs/json-schema-2019-09'>;
}
declare module 'ajv/dist/refs/json-schema-2019-09/index.js' {
  declare module.exports: $Exports<'ajv/dist/refs/json-schema-2019-09'>;
}
declare module 'ajv/dist/refs/json-schema-2020-12/index' {
  declare module.exports: $Exports<'ajv/dist/refs/json-schema-2020-12'>;
}
declare module 'ajv/dist/refs/json-schema-2020-12/index.js' {
  declare module.exports: $Exports<'ajv/dist/refs/json-schema-2020-12'>;
}
declare module 'ajv/dist/refs/jtd-schema.js' {
  declare module.exports: $Exports<'ajv/dist/refs/jtd-schema'>;
}
declare module 'ajv/dist/runtime/equal.js' {
  declare module.exports: $Exports<'ajv/dist/runtime/equal'>;
}
declare module 'ajv/dist/runtime/parseJson.js' {
  declare module.exports: $Exports<'ajv/dist/runtime/parseJson'>;
}
declare module 'ajv/dist/runtime/quote.js' {
  declare module.exports: $Exports<'ajv/dist/runtime/quote'>;
}
declare module 'ajv/dist/runtime/re2.js' {
  declare module.exports: $Exports<'ajv/dist/runtime/re2'>;
}
declare module 'ajv/dist/runtime/timestamp.js' {
  declare module.exports: $Exports<'ajv/dist/runtime/timestamp'>;
}
declare module 'ajv/dist/runtime/ucs2length.js' {
  declare module.exports: $Exports<'ajv/dist/runtime/ucs2length'>;
}
declare module 'ajv/dist/runtime/validation_error.js' {
  declare module.exports: $Exports<'ajv/dist/runtime/validation_error'>;
}
declare module 'ajv/dist/standalone/index' {
  declare module.exports: $Exports<'ajv/dist/standalone'>;
}
declare module 'ajv/dist/standalone/index.js' {
  declare module.exports: $Exports<'ajv/dist/standalone'>;
}
declare module 'ajv/dist/standalone/instance.js' {
  declare module.exports: $Exports<'ajv/dist/standalone/instance'>;
}
declare module 'ajv/dist/types/index' {
  declare module.exports: $Exports<'ajv/dist/types'>;
}
declare module 'ajv/dist/types/index.js' {
  declare module.exports: $Exports<'ajv/dist/types'>;
}
declare module 'ajv/dist/types/json-schema.js' {
  declare module.exports: $Exports<'ajv/dist/types/json-schema'>;
}
declare module 'ajv/dist/types/jtd-schema.js' {
  declare module.exports: $Exports<'ajv/dist/types/jtd-schema'>;
}
declare module 'ajv/dist/vocabularies/applicator/additionalItems.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/applicator/additionalItems'>;
}
declare module 'ajv/dist/vocabularies/applicator/additionalProperties.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/applicator/additionalProperties'>;
}
declare module 'ajv/dist/vocabularies/applicator/allOf.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/applicator/allOf'>;
}
declare module 'ajv/dist/vocabularies/applicator/anyOf.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/applicator/anyOf'>;
}
declare module 'ajv/dist/vocabularies/applicator/contains.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/applicator/contains'>;
}
declare module 'ajv/dist/vocabularies/applicator/dependencies.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/applicator/dependencies'>;
}
declare module 'ajv/dist/vocabularies/applicator/dependentSchemas.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/applicator/dependentSchemas'>;
}
declare module 'ajv/dist/vocabularies/applicator/if.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/applicator/if'>;
}
declare module 'ajv/dist/vocabularies/applicator/index' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/applicator'>;
}
declare module 'ajv/dist/vocabularies/applicator/index.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/applicator'>;
}
declare module 'ajv/dist/vocabularies/applicator/items.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/applicator/items'>;
}
declare module 'ajv/dist/vocabularies/applicator/items2020.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/applicator/items2020'>;
}
declare module 'ajv/dist/vocabularies/applicator/not.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/applicator/not'>;
}
declare module 'ajv/dist/vocabularies/applicator/oneOf.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/applicator/oneOf'>;
}
declare module 'ajv/dist/vocabularies/applicator/patternProperties.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/applicator/patternProperties'>;
}
declare module 'ajv/dist/vocabularies/applicator/prefixItems.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/applicator/prefixItems'>;
}
declare module 'ajv/dist/vocabularies/applicator/properties.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/applicator/properties'>;
}
declare module 'ajv/dist/vocabularies/applicator/propertyNames.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/applicator/propertyNames'>;
}
declare module 'ajv/dist/vocabularies/applicator/thenElse.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/applicator/thenElse'>;
}
declare module 'ajv/dist/vocabularies/code.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/code'>;
}
declare module 'ajv/dist/vocabularies/core/id.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/core/id'>;
}
declare module 'ajv/dist/vocabularies/core/index' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/core'>;
}
declare module 'ajv/dist/vocabularies/core/index.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/core'>;
}
declare module 'ajv/dist/vocabularies/core/ref.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/core/ref'>;
}
declare module 'ajv/dist/vocabularies/discriminator/index' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/discriminator'>;
}
declare module 'ajv/dist/vocabularies/discriminator/index.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/discriminator'>;
}
declare module 'ajv/dist/vocabularies/discriminator/types.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/discriminator/types'>;
}
declare module 'ajv/dist/vocabularies/draft2020.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/draft2020'>;
}
declare module 'ajv/dist/vocabularies/draft7.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/draft7'>;
}
declare module 'ajv/dist/vocabularies/dynamic/dynamicAnchor.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/dynamic/dynamicAnchor'>;
}
declare module 'ajv/dist/vocabularies/dynamic/dynamicRef.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/dynamic/dynamicRef'>;
}
declare module 'ajv/dist/vocabularies/dynamic/index' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/dynamic'>;
}
declare module 'ajv/dist/vocabularies/dynamic/index.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/dynamic'>;
}
declare module 'ajv/dist/vocabularies/dynamic/recursiveAnchor.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/dynamic/recursiveAnchor'>;
}
declare module 'ajv/dist/vocabularies/dynamic/recursiveRef.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/dynamic/recursiveRef'>;
}
declare module 'ajv/dist/vocabularies/errors.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/errors'>;
}
declare module 'ajv/dist/vocabularies/format/format.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/format/format'>;
}
declare module 'ajv/dist/vocabularies/format/index' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/format'>;
}
declare module 'ajv/dist/vocabularies/format/index.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/format'>;
}
declare module 'ajv/dist/vocabularies/jtd/discriminator.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/jtd/discriminator'>;
}
declare module 'ajv/dist/vocabularies/jtd/elements.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/jtd/elements'>;
}
declare module 'ajv/dist/vocabularies/jtd/enum.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/jtd/enum'>;
}
declare module 'ajv/dist/vocabularies/jtd/error.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/jtd/error'>;
}
declare module 'ajv/dist/vocabularies/jtd/index' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/jtd'>;
}
declare module 'ajv/dist/vocabularies/jtd/index.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/jtd'>;
}
declare module 'ajv/dist/vocabularies/jtd/metadata.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/jtd/metadata'>;
}
declare module 'ajv/dist/vocabularies/jtd/nullable.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/jtd/nullable'>;
}
declare module 'ajv/dist/vocabularies/jtd/optionalProperties.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/jtd/optionalProperties'>;
}
declare module 'ajv/dist/vocabularies/jtd/properties.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/jtd/properties'>;
}
declare module 'ajv/dist/vocabularies/jtd/ref.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/jtd/ref'>;
}
declare module 'ajv/dist/vocabularies/jtd/type.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/jtd/type'>;
}
declare module 'ajv/dist/vocabularies/jtd/union.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/jtd/union'>;
}
declare module 'ajv/dist/vocabularies/jtd/values.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/jtd/values'>;
}
declare module 'ajv/dist/vocabularies/metadata.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/metadata'>;
}
declare module 'ajv/dist/vocabularies/next.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/next'>;
}
declare module 'ajv/dist/vocabularies/unevaluated/index' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/unevaluated'>;
}
declare module 'ajv/dist/vocabularies/unevaluated/index.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/unevaluated'>;
}
declare module 'ajv/dist/vocabularies/unevaluated/unevaluatedItems.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/unevaluated/unevaluatedItems'>;
}
declare module 'ajv/dist/vocabularies/unevaluated/unevaluatedProperties.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/unevaluated/unevaluatedProperties'>;
}
declare module 'ajv/dist/vocabularies/validation/const.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/validation/const'>;
}
declare module 'ajv/dist/vocabularies/validation/dependentRequired.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/validation/dependentRequired'>;
}
declare module 'ajv/dist/vocabularies/validation/enum.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/validation/enum'>;
}
declare module 'ajv/dist/vocabularies/validation/index' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/validation'>;
}
declare module 'ajv/dist/vocabularies/validation/index.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/validation'>;
}
declare module 'ajv/dist/vocabularies/validation/limitContains.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/validation/limitContains'>;
}
declare module 'ajv/dist/vocabularies/validation/limitItems.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/validation/limitItems'>;
}
declare module 'ajv/dist/vocabularies/validation/limitLength.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/validation/limitLength'>;
}
declare module 'ajv/dist/vocabularies/validation/limitNumber.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/validation/limitNumber'>;
}
declare module 'ajv/dist/vocabularies/validation/limitProperties.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/validation/limitProperties'>;
}
declare module 'ajv/dist/vocabularies/validation/multipleOf.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/validation/multipleOf'>;
}
declare module 'ajv/dist/vocabularies/validation/pattern.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/validation/pattern'>;
}
declare module 'ajv/dist/vocabularies/validation/required.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/validation/required'>;
}
declare module 'ajv/dist/vocabularies/validation/uniqueItems.js' {
  declare module.exports: $Exports<'ajv/dist/vocabularies/validation/uniqueItems'>;
}
