// flow-typed signature: 23787ec5bf90f8c94ae88f2b14c1e3f8
// flow-typed version: <<STUB>>/babel-plugin-transform-flow-enums_v^0.0.2/flow_v0.167.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-flow-enums'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-flow-enums' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-flow-enums/__tests__/babel-plugin-transform-flow-enums-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-flow-enums/__tests__/babel-plugin-transform-flow-enums-test.js' {
  declare module.exports: $Exports<'babel-plugin-transform-flow-enums/__tests__/babel-plugin-transform-flow-enums-test'>;
}
declare module 'babel-plugin-transform-flow-enums/index' {
  declare module.exports: $Exports<'babel-plugin-transform-flow-enums'>;
}
declare module 'babel-plugin-transform-flow-enums/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-flow-enums'>;
}
