// flow-typed signature: 0ac63c6e0c2cb08037a3ed842cbc1f7d
// flow-typed version: <<STUB>>/eslint-plugin-testing-library_v^5.0.1/flow_v0.167.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-testing-library'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-testing-library' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-testing-library/configs/angular' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/configs/dom' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/configs' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/configs/react' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/configs/vue' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/create-testing-library-rule/detect-testing-library-utils' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/create-testing-library-rule' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/node-utils' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/node-utils/is-node-of-type' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/await-async-query' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/await-async-utils' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/await-fire-event' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/consistent-data-testid' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/no-await-sync-events' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/no-await-sync-query' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/no-container' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/no-debugging-utils' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/no-dom-import' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/no-manual-cleanup' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/no-node-access' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/no-promise-in-fire-event' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/no-render-in-setup' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/no-unnecessary-act' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/no-wait-for-empty-callback' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/no-wait-for-multiple-assertions' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/no-wait-for-side-effects' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/no-wait-for-snapshot' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/prefer-explicit-assert' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/prefer-find-by' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/prefer-presence-queries' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/prefer-query-by-disappearance' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/prefer-screen-queries' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/prefer-user-event' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/prefer-wait-for' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/rules/render-result-naming-convention' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/utils/file-import' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/utils' {
  declare module.exports: any;
}

declare module 'eslint-plugin-testing-library/utils/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-testing-library/configs/angular.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/configs/angular'>;
}
declare module 'eslint-plugin-testing-library/configs/dom.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/configs/dom'>;
}
declare module 'eslint-plugin-testing-library/configs/index' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/configs'>;
}
declare module 'eslint-plugin-testing-library/configs/index.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/configs'>;
}
declare module 'eslint-plugin-testing-library/configs/react.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/configs/react'>;
}
declare module 'eslint-plugin-testing-library/configs/vue.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/configs/vue'>;
}
declare module 'eslint-plugin-testing-library/create-testing-library-rule/detect-testing-library-utils.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/create-testing-library-rule/detect-testing-library-utils'>;
}
declare module 'eslint-plugin-testing-library/create-testing-library-rule/index' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/create-testing-library-rule'>;
}
declare module 'eslint-plugin-testing-library/create-testing-library-rule/index.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/create-testing-library-rule'>;
}
declare module 'eslint-plugin-testing-library/index' {
  declare module.exports: $Exports<'eslint-plugin-testing-library'>;
}
declare module 'eslint-plugin-testing-library/index.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library'>;
}
declare module 'eslint-plugin-testing-library/node-utils/index' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/node-utils'>;
}
declare module 'eslint-plugin-testing-library/node-utils/index.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/node-utils'>;
}
declare module 'eslint-plugin-testing-library/node-utils/is-node-of-type.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/node-utils/is-node-of-type'>;
}
declare module 'eslint-plugin-testing-library/rules/await-async-query.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/await-async-query'>;
}
declare module 'eslint-plugin-testing-library/rules/await-async-utils.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/await-async-utils'>;
}
declare module 'eslint-plugin-testing-library/rules/await-fire-event.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/await-fire-event'>;
}
declare module 'eslint-plugin-testing-library/rules/consistent-data-testid.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/consistent-data-testid'>;
}
declare module 'eslint-plugin-testing-library/rules/index' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules'>;
}
declare module 'eslint-plugin-testing-library/rules/index.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules'>;
}
declare module 'eslint-plugin-testing-library/rules/no-await-sync-events.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/no-await-sync-events'>;
}
declare module 'eslint-plugin-testing-library/rules/no-await-sync-query.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/no-await-sync-query'>;
}
declare module 'eslint-plugin-testing-library/rules/no-container.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/no-container'>;
}
declare module 'eslint-plugin-testing-library/rules/no-debugging-utils.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/no-debugging-utils'>;
}
declare module 'eslint-plugin-testing-library/rules/no-dom-import.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/no-dom-import'>;
}
declare module 'eslint-plugin-testing-library/rules/no-manual-cleanup.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/no-manual-cleanup'>;
}
declare module 'eslint-plugin-testing-library/rules/no-node-access.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/no-node-access'>;
}
declare module 'eslint-plugin-testing-library/rules/no-promise-in-fire-event.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/no-promise-in-fire-event'>;
}
declare module 'eslint-plugin-testing-library/rules/no-render-in-setup.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/no-render-in-setup'>;
}
declare module 'eslint-plugin-testing-library/rules/no-unnecessary-act.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/no-unnecessary-act'>;
}
declare module 'eslint-plugin-testing-library/rules/no-wait-for-empty-callback.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/no-wait-for-empty-callback'>;
}
declare module 'eslint-plugin-testing-library/rules/no-wait-for-multiple-assertions.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/no-wait-for-multiple-assertions'>;
}
declare module 'eslint-plugin-testing-library/rules/no-wait-for-side-effects.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/no-wait-for-side-effects'>;
}
declare module 'eslint-plugin-testing-library/rules/no-wait-for-snapshot.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/no-wait-for-snapshot'>;
}
declare module 'eslint-plugin-testing-library/rules/prefer-explicit-assert.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/prefer-explicit-assert'>;
}
declare module 'eslint-plugin-testing-library/rules/prefer-find-by.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/prefer-find-by'>;
}
declare module 'eslint-plugin-testing-library/rules/prefer-presence-queries.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/prefer-presence-queries'>;
}
declare module 'eslint-plugin-testing-library/rules/prefer-query-by-disappearance.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/prefer-query-by-disappearance'>;
}
declare module 'eslint-plugin-testing-library/rules/prefer-screen-queries.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/prefer-screen-queries'>;
}
declare module 'eslint-plugin-testing-library/rules/prefer-user-event.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/prefer-user-event'>;
}
declare module 'eslint-plugin-testing-library/rules/prefer-wait-for.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/prefer-wait-for'>;
}
declare module 'eslint-plugin-testing-library/rules/render-result-naming-convention.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/rules/render-result-naming-convention'>;
}
declare module 'eslint-plugin-testing-library/utils/file-import.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/utils/file-import'>;
}
declare module 'eslint-plugin-testing-library/utils/index' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/utils'>;
}
declare module 'eslint-plugin-testing-library/utils/index.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/utils'>;
}
declare module 'eslint-plugin-testing-library/utils/types.js' {
  declare module.exports: $Exports<'eslint-plugin-testing-library/utils/types'>;
}
