// flow-typed signature: 65c82ab5e500f8a48ae94acae911f339
// flow-typed version: <<STUB>>/eslint_v^8.1.0/flow_v0.167.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint' {
  declare type Rule$Context = {|
    report: ({ ... }) => void,
    getAllComments: () => Array<{|
      type: string,
      value: string,
    |}>,
    getSourceCode: () => Rule$Context,
  |};

  declare type Rule$Create = (context: Rule$Context) => {|
    [key: string]: any,
  |};

  declare class RuleTester {
    constructor(config?: {|
      [key: string]: any,
    |}): this;

    static describe(title: string, fn: () => void): void;
    static it(title: string, fn: () => void): void;

    run(...args: Array<any>): this;
  }

  declare module.exports: {
    RuleTester: typeof RuleTester,
  };
}
