// flow-typed signature: f142e1b5717bab78c0aabc21a4685c6d
// flow-typed version: <<STUB>>/eslint-plugin-fb-flow_v^0.0.4/flow_v0.167.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-fb-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-fb-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-fb-flow/rules/flow-enums-default-if-possible' {
  declare module.exports: any;
}

declare module 'eslint-plugin-fb-flow/rules/no-flow-enums-object-mapping' {
  declare module.exports: any;
}

declare module 'eslint-plugin-fb-flow/rules/use-exact-by-default-object-type' {
  declare module.exports: any;
}

declare module 'eslint-plugin-fb-flow/rules/use-flow-enums' {
  declare module.exports: any;
}

declare module 'eslint-plugin-fb-flow/rules/use-indexed-access-type' {
  declare module.exports: any;
}

declare module 'eslint-plugin-fb-flow/run-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-fb-flow/index' {
  declare module.exports: $Exports<'eslint-plugin-fb-flow'>;
}
declare module 'eslint-plugin-fb-flow/index.js' {
  declare module.exports: $Exports<'eslint-plugin-fb-flow'>;
}
declare module 'eslint-plugin-fb-flow/rules/flow-enums-default-if-possible.js' {
  declare module.exports: $Exports<'eslint-plugin-fb-flow/rules/flow-enums-default-if-possible'>;
}
declare module 'eslint-plugin-fb-flow/rules/no-flow-enums-object-mapping.js' {
  declare module.exports: $Exports<'eslint-plugin-fb-flow/rules/no-flow-enums-object-mapping'>;
}
declare module 'eslint-plugin-fb-flow/rules/use-exact-by-default-object-type.js' {
  declare module.exports: $Exports<'eslint-plugin-fb-flow/rules/use-exact-by-default-object-type'>;
}
declare module 'eslint-plugin-fb-flow/rules/use-flow-enums.js' {
  declare module.exports: $Exports<'eslint-plugin-fb-flow/rules/use-flow-enums'>;
}
declare module 'eslint-plugin-fb-flow/rules/use-indexed-access-type.js' {
  declare module.exports: $Exports<'eslint-plugin-fb-flow/rules/use-indexed-access-type'>;
}
declare module 'eslint-plugin-fb-flow/run-test.js' {
  declare module.exports: $Exports<'eslint-plugin-fb-flow/run-test'>;
}
