// flow-typed signature: 480d4607c7c8f297c5fd0d3c9b65fee2
// flow-typed version: <<STUB>>/eslint-plugin-eslint-plugin_v^4.0.2/flow_v0.167.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-eslint-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-eslint-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-eslint-plugin/lib' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-plugin/lib/rules/consistent-output' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-plugin/lib/rules/fixer-return' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-plugin/lib/rules/meta-property-ordering' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-plugin/lib/rules/no-deprecated-context-methods' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-plugin/lib/rules/no-deprecated-report-api' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-plugin/lib/rules/no-identical-tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-plugin/lib/rules/no-missing-placeholders' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-plugin/lib/rules/no-only-tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-plugin/lib/rules/no-unused-placeholders' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-plugin/lib/rules/no-useless-token-range' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-plugin/lib/rules/prefer-message-ids' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-plugin/lib/rules/prefer-object-rule' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-plugin/lib/rules/prefer-output-null' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-plugin/lib/rules/prefer-placeholders' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-plugin/lib/rules/prefer-replace-text' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-plugin/lib/rules/report-message-format' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-plugin/lib/rules/require-meta-docs-description' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-plugin/lib/rules/require-meta-docs-url' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-plugin/lib/rules/require-meta-fixable' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-plugin/lib/rules/require-meta-has-suggestions' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-plugin/lib/rules/require-meta-schema' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-plugin/lib/rules/require-meta-type' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-plugin/lib/rules/test-case-property-ordering' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-plugin/lib/rules/test-case-shorthand-strings' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-plugin/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-eslint-plugin/lib/index' {
  declare module.exports: $Exports<'eslint-plugin-eslint-plugin/lib'>;
}
declare module 'eslint-plugin-eslint-plugin/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-plugin/lib'>;
}
declare module 'eslint-plugin-eslint-plugin/lib/rules/consistent-output.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-plugin/lib/rules/consistent-output'>;
}
declare module 'eslint-plugin-eslint-plugin/lib/rules/fixer-return.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-plugin/lib/rules/fixer-return'>;
}
declare module 'eslint-plugin-eslint-plugin/lib/rules/meta-property-ordering.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-plugin/lib/rules/meta-property-ordering'>;
}
declare module 'eslint-plugin-eslint-plugin/lib/rules/no-deprecated-context-methods.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-plugin/lib/rules/no-deprecated-context-methods'>;
}
declare module 'eslint-plugin-eslint-plugin/lib/rules/no-deprecated-report-api.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-plugin/lib/rules/no-deprecated-report-api'>;
}
declare module 'eslint-plugin-eslint-plugin/lib/rules/no-identical-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-plugin/lib/rules/no-identical-tests'>;
}
declare module 'eslint-plugin-eslint-plugin/lib/rules/no-missing-placeholders.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-plugin/lib/rules/no-missing-placeholders'>;
}
declare module 'eslint-plugin-eslint-plugin/lib/rules/no-only-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-plugin/lib/rules/no-only-tests'>;
}
declare module 'eslint-plugin-eslint-plugin/lib/rules/no-unused-placeholders.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-plugin/lib/rules/no-unused-placeholders'>;
}
declare module 'eslint-plugin-eslint-plugin/lib/rules/no-useless-token-range.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-plugin/lib/rules/no-useless-token-range'>;
}
declare module 'eslint-plugin-eslint-plugin/lib/rules/prefer-message-ids.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-plugin/lib/rules/prefer-message-ids'>;
}
declare module 'eslint-plugin-eslint-plugin/lib/rules/prefer-object-rule.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-plugin/lib/rules/prefer-object-rule'>;
}
declare module 'eslint-plugin-eslint-plugin/lib/rules/prefer-output-null.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-plugin/lib/rules/prefer-output-null'>;
}
declare module 'eslint-plugin-eslint-plugin/lib/rules/prefer-placeholders.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-plugin/lib/rules/prefer-placeholders'>;
}
declare module 'eslint-plugin-eslint-plugin/lib/rules/prefer-replace-text.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-plugin/lib/rules/prefer-replace-text'>;
}
declare module 'eslint-plugin-eslint-plugin/lib/rules/report-message-format.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-plugin/lib/rules/report-message-format'>;
}
declare module 'eslint-plugin-eslint-plugin/lib/rules/require-meta-docs-description.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-plugin/lib/rules/require-meta-docs-description'>;
}
declare module 'eslint-plugin-eslint-plugin/lib/rules/require-meta-docs-url.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-plugin/lib/rules/require-meta-docs-url'>;
}
declare module 'eslint-plugin-eslint-plugin/lib/rules/require-meta-fixable.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-plugin/lib/rules/require-meta-fixable'>;
}
declare module 'eslint-plugin-eslint-plugin/lib/rules/require-meta-has-suggestions.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-plugin/lib/rules/require-meta-has-suggestions'>;
}
declare module 'eslint-plugin-eslint-plugin/lib/rules/require-meta-schema.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-plugin/lib/rules/require-meta-schema'>;
}
declare module 'eslint-plugin-eslint-plugin/lib/rules/require-meta-type.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-plugin/lib/rules/require-meta-type'>;
}
declare module 'eslint-plugin-eslint-plugin/lib/rules/test-case-property-ordering.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-plugin/lib/rules/test-case-property-ordering'>;
}
declare module 'eslint-plugin-eslint-plugin/lib/rules/test-case-shorthand-strings.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-plugin/lib/rules/test-case-shorthand-strings'>;
}
declare module 'eslint-plugin-eslint-plugin/lib/utils.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-plugin/lib/utils'>;
}
