// flow-typed signature: aee0539f8565f723b286aa12049069a2
// flow-typed version: <<STUB>>/eslint-config-airbnb_v^19.0.2/flow_v0.167.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-airbnb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-airbnb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-airbnb/base' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb/hooks' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb/legacy' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb/rules/react-a11y' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb/rules/react-hooks' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb/rules/react' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb/test/requires' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb/test/test-base' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb/test/test-react-order' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb/whitespace-async' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb/whitespace' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb/whitespaceRules' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-airbnb/base.js' {
  declare module.exports: $Exports<'eslint-config-airbnb/base'>;
}
declare module 'eslint-config-airbnb/hooks.js' {
  declare module.exports: $Exports<'eslint-config-airbnb/hooks'>;
}
declare module 'eslint-config-airbnb/index' {
  declare module.exports: $Exports<'eslint-config-airbnb'>;
}
declare module 'eslint-config-airbnb/index.js' {
  declare module.exports: $Exports<'eslint-config-airbnb'>;
}
declare module 'eslint-config-airbnb/legacy.js' {
  declare module.exports: $Exports<'eslint-config-airbnb/legacy'>;
}
declare module 'eslint-config-airbnb/rules/react-a11y.js' {
  declare module.exports: $Exports<'eslint-config-airbnb/rules/react-a11y'>;
}
declare module 'eslint-config-airbnb/rules/react-hooks.js' {
  declare module.exports: $Exports<'eslint-config-airbnb/rules/react-hooks'>;
}
declare module 'eslint-config-airbnb/rules/react.js' {
  declare module.exports: $Exports<'eslint-config-airbnb/rules/react'>;
}
declare module 'eslint-config-airbnb/test/requires.js' {
  declare module.exports: $Exports<'eslint-config-airbnb/test/requires'>;
}
declare module 'eslint-config-airbnb/test/test-base.js' {
  declare module.exports: $Exports<'eslint-config-airbnb/test/test-base'>;
}
declare module 'eslint-config-airbnb/test/test-react-order.js' {
  declare module.exports: $Exports<'eslint-config-airbnb/test/test-react-order'>;
}
declare module 'eslint-config-airbnb/whitespace-async.js' {
  declare module.exports: $Exports<'eslint-config-airbnb/whitespace-async'>;
}
declare module 'eslint-config-airbnb/whitespace.js' {
  declare module.exports: $Exports<'eslint-config-airbnb/whitespace'>;
}
declare module 'eslint-config-airbnb/whitespaceRules.js' {
  declare module.exports: $Exports<'eslint-config-airbnb/whitespaceRules'>;
}
