// flow-typed signature: 3ba33ddf4b22ca0706dd0d1d7520cba4
// flow-typed version: <<STUB>>/eslint-config-canonical_v^32.15.0/flow_v0.167.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-canonical'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-canonical' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-canonical/ava' {
  declare module.exports: any;
}

declare module 'eslint-config-canonical/bin/generate-typescript-compatibility-rules' {
  declare module.exports: any;
}

declare module 'eslint-config-canonical/browser' {
  declare module.exports: any;
}

declare module 'eslint-config-canonical/compare/compare' {
  declare module.exports: any;
}

declare module 'eslint-config-canonical/compare/find-deprecated' {
  declare module.exports: any;
}

declare module 'eslint-config-canonical/compare/utilities' {
  declare module.exports: any;
}

declare module 'eslint-config-canonical/cypress' {
  declare module.exports: any;
}

declare module 'eslint-config-canonical/eslintrc' {
  declare module.exports: any;
}

declare module 'eslint-config-canonical/flowtype' {
  declare module.exports: any;
}

declare module 'eslint-config-canonical/jest' {
  declare module.exports: any;
}

declare module 'eslint-config-canonical/json' {
  declare module.exports: any;
}

declare module 'eslint-config-canonical/jsx-a11y' {
  declare module.exports: any;
}

declare module 'eslint-config-canonical/lodash' {
  declare module.exports: any;
}

declare module 'eslint-config-canonical/mocha' {
  declare module.exports: any;
}

declare module 'eslint-config-canonical/module' {
  declare module.exports: any;
}

declare module 'eslint-config-canonical/next' {
  declare module.exports: any;
}

declare module 'eslint-config-canonical/node' {
  declare module.exports: any;
}

declare module 'eslint-config-canonical/react' {
  declare module.exports: any;
}

declare module 'eslint-config-canonical/test/eslint-config-canonical/canonical' {
  declare module.exports: any;
}

declare module 'eslint-config-canonical/typescript' {
  declare module.exports: any;
}

declare module 'eslint-config-canonical/yaml' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-canonical/ava.js' {
  declare module.exports: $Exports<'eslint-config-canonical/ava'>;
}
declare module 'eslint-config-canonical/bin/generate-typescript-compatibility-rules.js' {
  declare module.exports: $Exports<'eslint-config-canonical/bin/generate-typescript-compatibility-rules'>;
}
declare module 'eslint-config-canonical/browser.js' {
  declare module.exports: $Exports<'eslint-config-canonical/browser'>;
}
declare module 'eslint-config-canonical/compare/compare.js' {
  declare module.exports: $Exports<'eslint-config-canonical/compare/compare'>;
}
declare module 'eslint-config-canonical/compare/find-deprecated.js' {
  declare module.exports: $Exports<'eslint-config-canonical/compare/find-deprecated'>;
}
declare module 'eslint-config-canonical/compare/utilities.js' {
  declare module.exports: $Exports<'eslint-config-canonical/compare/utilities'>;
}
declare module 'eslint-config-canonical/cypress.js' {
  declare module.exports: $Exports<'eslint-config-canonical/cypress'>;
}
declare module 'eslint-config-canonical/eslintrc.js' {
  declare module.exports: $Exports<'eslint-config-canonical/eslintrc'>;
}
declare module 'eslint-config-canonical/flowtype.js' {
  declare module.exports: $Exports<'eslint-config-canonical/flowtype'>;
}
declare module 'eslint-config-canonical/jest.js' {
  declare module.exports: $Exports<'eslint-config-canonical/jest'>;
}
declare module 'eslint-config-canonical/json.js' {
  declare module.exports: $Exports<'eslint-config-canonical/json'>;
}
declare module 'eslint-config-canonical/jsx-a11y.js' {
  declare module.exports: $Exports<'eslint-config-canonical/jsx-a11y'>;
}
declare module 'eslint-config-canonical/lodash.js' {
  declare module.exports: $Exports<'eslint-config-canonical/lodash'>;
}
declare module 'eslint-config-canonical/mocha.js' {
  declare module.exports: $Exports<'eslint-config-canonical/mocha'>;
}
declare module 'eslint-config-canonical/module.js' {
  declare module.exports: $Exports<'eslint-config-canonical/module'>;
}
declare module 'eslint-config-canonical/next.js' {
  declare module.exports: $Exports<'eslint-config-canonical/next'>;
}
declare module 'eslint-config-canonical/node.js' {
  declare module.exports: $Exports<'eslint-config-canonical/node'>;
}
declare module 'eslint-config-canonical/react.js' {
  declare module.exports: $Exports<'eslint-config-canonical/react'>;
}
declare module 'eslint-config-canonical/test/eslint-config-canonical/canonical.js' {
  declare module.exports: $Exports<'eslint-config-canonical/test/eslint-config-canonical/canonical'>;
}
declare module 'eslint-config-canonical/typescript.js' {
  declare module.exports: $Exports<'eslint-config-canonical/typescript'>;
}
declare module 'eslint-config-canonical/yaml.js' {
  declare module.exports: $Exports<'eslint-config-canonical/yaml'>;
}
