// flow-typed signature: 7831c3c852807cccc8e15a7b54067ca3
// flow-typed version: <<STUB>>/gitdown_v^3.1.4/flow_v0.167.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gitdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gitdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gitdown/dist/bin' {
  declare module.exports: any;
}

declare module 'gitdown/dist/gitdown' {
  declare module.exports: any;
}

declare module 'gitdown/dist/helpers/badge' {
  declare module.exports: any;
}

declare module 'gitdown/dist/helpers/contents' {
  declare module.exports: any;
}

declare module 'gitdown/dist/helpers/date' {
  declare module.exports: any;
}

declare module 'gitdown/dist/helpers/deadlink' {
  declare module.exports: any;
}

declare module 'gitdown/dist/helpers/filesize' {
  declare module.exports: any;
}

declare module 'gitdown/dist/helpers/gitinfo' {
  declare module.exports: any;
}

declare module 'gitdown/dist/helpers/include' {
  declare module.exports: any;
}

declare module 'gitdown/dist/helpers/test' {
  declare module.exports: any;
}

declare module 'gitdown/dist/helpers/variable' {
  declare module.exports: any;
}

declare module 'gitdown/dist' {
  declare module.exports: any;
}

declare module 'gitdown/dist/locator' {
  declare module.exports: any;
}

declare module 'gitdown/dist/parser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gitdown/dist/bin/index' {
  declare module.exports: $Exports<'gitdown/dist/bin'>;
}
declare module 'gitdown/dist/bin/index.js' {
  declare module.exports: $Exports<'gitdown/dist/bin'>;
}
declare module 'gitdown/dist/gitdown.js' {
  declare module.exports: $Exports<'gitdown/dist/gitdown'>;
}
declare module 'gitdown/dist/helpers/badge.js' {
  declare module.exports: $Exports<'gitdown/dist/helpers/badge'>;
}
declare module 'gitdown/dist/helpers/contents.js' {
  declare module.exports: $Exports<'gitdown/dist/helpers/contents'>;
}
declare module 'gitdown/dist/helpers/date.js' {
  declare module.exports: $Exports<'gitdown/dist/helpers/date'>;
}
declare module 'gitdown/dist/helpers/deadlink.js' {
  declare module.exports: $Exports<'gitdown/dist/helpers/deadlink'>;
}
declare module 'gitdown/dist/helpers/filesize.js' {
  declare module.exports: $Exports<'gitdown/dist/helpers/filesize'>;
}
declare module 'gitdown/dist/helpers/gitinfo.js' {
  declare module.exports: $Exports<'gitdown/dist/helpers/gitinfo'>;
}
declare module 'gitdown/dist/helpers/include.js' {
  declare module.exports: $Exports<'gitdown/dist/helpers/include'>;
}
declare module 'gitdown/dist/helpers/test.js' {
  declare module.exports: $Exports<'gitdown/dist/helpers/test'>;
}
declare module 'gitdown/dist/helpers/variable.js' {
  declare module.exports: $Exports<'gitdown/dist/helpers/variable'>;
}
declare module 'gitdown/dist/index' {
  declare module.exports: $Exports<'gitdown/dist'>;
}
declare module 'gitdown/dist/index.js' {
  declare module.exports: $Exports<'gitdown/dist'>;
}
declare module 'gitdown/dist/locator.js' {
  declare module.exports: $Exports<'gitdown/dist/locator'>;
}
declare module 'gitdown/dist/parser.js' {
  declare module.exports: $Exports<'gitdown/dist/parser'>;
}
