// flow-typed signature: a68fef8076a35ce887e148b4aee1d7b1
// flow-typed version: <<STUB>>/jsonlint-mod_v^1.7.6/flow_v0.167.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsonlint-mod'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsonlint-mod' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsonlint-mod/lib/cli' {
  declare module.exports: any;
}

declare module 'jsonlint-mod/lib/doug-json-parse' {
  declare module.exports: any;
}

declare module 'jsonlint-mod/lib/formatter' {
  declare module.exports: any;
}

declare module 'jsonlint-mod/lib/jsonlint' {
  declare module.exports: any;
}

declare module 'jsonlint-mod/lib/nomnom' {
  declare module.exports: any;
}

declare module 'jsonlint-mod/scripts/bundle' {
  declare module.exports: any;
}

declare module 'jsonlint-mod/test/all-tests' {
  declare module.exports: any;
}

declare module 'jsonlint-mod/web/json2' {
  declare module.exports: any;
}

declare module 'jsonlint-mod/web/jsonlint' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsonlint-mod/lib/cli.js' {
  declare module.exports: $Exports<'jsonlint-mod/lib/cli'>;
}
declare module 'jsonlint-mod/lib/doug-json-parse.js' {
  declare module.exports: $Exports<'jsonlint-mod/lib/doug-json-parse'>;
}
declare module 'jsonlint-mod/lib/formatter.js' {
  declare module.exports: $Exports<'jsonlint-mod/lib/formatter'>;
}
declare module 'jsonlint-mod/lib/jsonlint.js' {
  declare module.exports: $Exports<'jsonlint-mod/lib/jsonlint'>;
}
declare module 'jsonlint-mod/lib/nomnom.js' {
  declare module.exports: $Exports<'jsonlint-mod/lib/nomnom'>;
}
declare module 'jsonlint-mod/scripts/bundle.js' {
  declare module.exports: $Exports<'jsonlint-mod/scripts/bundle'>;
}
declare module 'jsonlint-mod/test/all-tests.js' {
  declare module.exports: $Exports<'jsonlint-mod/test/all-tests'>;
}
declare module 'jsonlint-mod/web/json2.js' {
  declare module.exports: $Exports<'jsonlint-mod/web/json2'>;
}
declare module 'jsonlint-mod/web/jsonlint.js' {
  declare module.exports: $Exports<'jsonlint-mod/web/jsonlint'>;
}
