// flow-typed signature: 6ca010207e259fdf60b76c93ba83c17f
// flow-typed version: <<STUB>>/string-natural-compare_v^3.0.1/flow_v0.167.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'string-natural-compare'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'string-natural-compare' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'string-natural-compare/natural-compare' {
  declare module.exports: any;
}

// Filename aliases
declare module 'string-natural-compare/natural-compare.js' {
  declare module.exports: $Exports<'string-natural-compare/natural-compare'>;
}
