// flow-typed signature: 205f6425f7cb219ad5b61b1d819380af
// flow-typed version: <<STUB>>/@babel/eslint-parser_v^7.12.0/flow_v0.167.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/eslint-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/eslint-parser' {
  declare module.exports: any;
}
